### PR TITLE
fix: add Windows tests (take 2)

### LINKED ISSUE #5: TODO: test on real device libraries
we should include just the `DemoCamera.dll` (or `.so`) and the `MMDemoConfig.cfg` file from the built micromanager distribution in our `tests` folder so we can test that the core drives real devices

### PR DESCRIPTION
**Pull request by jacopoabramo**
Addresses the previously closed PR for adding testing support for Windows, see #5 

I added a couple of tests:

- one for a camera snap (it's still very rough because it returns a `PyCapsule` object while I believe there should be a `TaggedImage` type if I recall. But at least the object is not empty so that's a start).
- one for camera ROI get/set; this one I marked as skipped because there's an inconsistency with the declared return type of the built package; basically meson will change the signature from `tuple` to `std::tuple<int,int,int,int>` and python doesn't know what to do with it.

An extra remark:

- we should add a `TIMESTAMP` text file which marks the latest micromanager version against which `pmn` was tested. Especially because nightly builds may change the behavior somehow (I don't expect this to happen but it would be good practice just in case).

closes #5

### CODE REVIEW

**Comment by tlambert03** [comment]
yay!!  thank you !

>  I believe there should be a TaggedImage type if I recal

`TaggedImage` is actually a Java-only construct... not something we would implement here. `getImage` needs to return a numpy array... and that's issue #1 

[Here](https://github.com/pymmcore-plus/pymmdevice/blob/83e04c8da3b898b5fb7696a2b9d083b476307dc0/src/bindings/utils.h#L18-L38) is some prior code (for pybind11) that you can look at... and [here](https://github.com/pymmcore-plus/pymmdevice/blob/83e04c8da3b898b5fb7696a2b9d083b476307dc0/src/bindings/_pymmdevice.cpp#L585-L591) is where it was invoked.  but that will need a bit of changing to go from pybind11 to nanobind.  And, for reference, [here](https://github.com/micro-manager/pymmcore/blob/369573b5fe862feb039ae0c2f54a6c7974fa004d/src/pymmcore/pymmcore_swig.i#L56-L142) is how we do it in `pymmcore` (the implication there is that *any* `void*` pointer should be cast to a numpy array using that logic 

> there's an inconsistency with the declared return type of the built package

i did do a slightly hacky patch on that in #7, so the generated type stubs are now actually correct again... (but only because I'm manually parsing/fixing the generated type stubs until we figure out how to tell nanobind.stubgen to do it itself)

> we should add a TIMESTAMP text file which marks the latest micromanager version against which pmn was tested.

this is a great idea.  i will go back and add that for the adapters I added.  Note though, the built adapter binaries themselves should also have [the device interface](https://github.com/micro-manager/mmCoreAndDevices/blob/870fdb121ba977ab00fb1032cab320457a811cf1/MMDevice/MMDevice.h#L31) number embedded in them.  Which we can much up at build-time to see whether we're out of sync.  That's the most important thing to keep in check

**Comment by tlambert03** [comment]
ahhh sorry, I just pulled this and now I see what you meant by getROI:

```python
>       roi = mmc.getROI()
E       TypeError: Unable to convert function return value to a Python type! The signature was
E           getROI(self) -> std::__1::tuple<int, int, int, int>
```

This is because nanobind requires you to [explicitly import typecasters](https://nanobind.readthedocs.io/en/latest/exchanging.html#option-1-type-casters) for all of the python types you need to support.  So we just need to add `#include <nanobind/stl/tuple.h>` to `_pymmcore_nano.cc` and then your test passes

**Comment by jacopoabramo** [comment]
> it's probably best if you create a branch for your PRs

duly noted; it's definetely the best practice to follow but I always tend to rush things up. i'll be more careful!

**Comment by tlambert03** [comment]
> i'll be more careful!

don't worry on my behalf! :)  it's more a tip for your sake, since it can be harder to resolve conflicts on main and stuff.   but I'm grateful for any and all interaction :)

**Pull request merged**
